# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-TWSMS
version:      0.01
version_from: lib/WWW/TWSMS.pm
installdirs:  site
requires:
    HTTP::Cookies:                 1.39
    HTTP::Request::Common:         1.26
    LWP::UserAgent:                2.033

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
